# back-Despachos_SpringBoot/k8s/deployment-despachos.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: innovatech
  labels:
    app: backend-despachos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
        - name: backend-despachos
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/back-despachos-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: SERVER_PORT
              value: "8080"
            - name: PORT
              value: "8080"
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_ENDPOINT
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: API_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: despachos-service
  namespace: innovatech
spec:
  type: ClusterIP
  selector:
    app: backend-despachos
  ports:
    - port: 80
      targetPort: 8080
